//「ファイルパスとファイル名」「表示するテキスト」の順で用意した音声パーツの情報を入力してください。
//予め入力されているサンプルを参考に入力してください。
//1行1文節で設定してください。
//無音パーツは流用して使っていただいても構いません。
//ダブルクォートや括弧、カンマ記号に1文字でも不備があると正しく読み込ませません。
soundData =
[
 // ["sound/yokoku-chime.mp3", "(♪予告メロディ)"],
 // ["sound/21ji.mp3", "21時"],
 // ["sound/22hun-hatsu.mp3", "22分発"],
 // ["sound/local.mp3", "普通"],
 // ["sound/kamo-yukiha.mp3", "加茂行きは"],
 // ["sound/1bannoriba-kara.mp3", "1番のりばから"],
 // ["sound/hasshashimasu.mp3", "発車します"],
 ["sound/ATOS_sekkinn.mp3", "接近メロディ"],
 ["sound/atos/goodmorning.mp3", "おはようございます"],
 ["sound/atos/kondono.mp3", "今度の"],

 ["sound/atos/1bansenno.mp3", "1番線の"],
 ["sound/atos/.mp3", "2番線の"],
 ["sound/atos/.mp3", "3番線の"],
 ["sound/atos/.mp3", "4番線の"],
 ["sound/atos/.mp3", "5番線の"],
 ["sound/atos/.mp3", "6番線の"],
 ["sound/atos/.mp3", "7番線の"],
 ["sound/atos/.mp3", "8番線の"],
 ["sound/atos/.mp3", "9番線の"],
 ["sound/atos/.mp3", "10番線の"],
 ["sound/atos/.mp3", "11番線の"],
 ["sound/atos/.mp3", "12番線の"],
 ["sound/atos/.mp3", "13番線の"],
 ["sound/atos/.mp3", "14番線の"],
 ["sound/atos/.mp3", "15番線の"],
 ["sound/atos/.mp3", "16番線の"],
 ["sound/atos/.mp3", "17番線の"],
 ["sound/atos/.mp3", "18番線の"],
 ["sound/atos/.mp3", "19番線の"],
 ["sound/atos/.mp3", "20番線の"],
 ["sound/atos/.mp3", "21番線の"],
 ["sound/atos/.mp3", "22番線の"],

 ["sound/atos/ressyaha.mp3", "列車は"],
 ["sound/atos/densyaha.mp3", "電車は"],
 ["sound/atos/10.mp3", "10"],
 ["sound/atos/20.mp3", "20"],
 ["sound/atos/1ji.mp3", "1時"],
 ["sound/atos/2ji.mp3", "2時"],
 ["sound/atos/3ji.mp3", "3時"],
 ["sound/atos/4ji.mp3", "4時"],
 ["sound/atos/5ji.mp3", "5時"],
 ["sound/atos/6ji.mp3", "6時"],
 ["sound/atos/7ji.mp3", "7時"],
 ["sound/atos/8ji.mp3", "8時"],
 ["sound/atos/9ji.mp3", "9時"],
 ["sound/atos/10ji.mp3", "10時"],
 ["sound/atos/20ji.mp3", "20時"],
 ["sound/atos/1fun.mp3", "1分"],
 ["sound/atos/2fun.mp3", "2分"],
 ["sound/atos/3fun.mp3", "3分"],
 ["sound/atos/4fun.mp3", "4分"],
 ["sound/atos/5fun.mp3", "5分"],
 ["sound/atos/6fun.mp3", "6分"],
 ["sound/atos/7fun.mp3", "7分"],
 ["sound/atos/8fun.mp3", "8分"],
 ["sound/atos/9fun.mp3", "9分"],
 ["sound/atos/10fun.mp3", "10分"],
 ["sound/atos/20fun.mp3", "20分"],
 ["sound/atos/30fun.mp3", "30分"],
 ["sound/atos/40fun.mp3", "40分"],
 ["sound/atos/50fun.mp3", "50分"],
 ["sound/atos/10.mp3", "10"],
 ["sound/atos/20.mp3", "20"],
 ["sound/atos/30.mp3", "30"],
 ["sound/atos/40.mp3", "40"],
 ["sound/atos/50.mp3", "50"],
 ["sound/atos/hatsu.mp3", "発"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/local.mp3", "普通"],
 ["sound/atos/kakutei.mp3", "各駅停車"],
 ["sound/atos/rapid.mp3", "快速"],
 ["sound/atos/sprapid.mp3", "特別快速"],
 ["sound/atos/exp.mp3", "急行"],
 ["sound/atos/ltd.mp3", "特急"],
 ["sound/atos/sindaitokyu.mp3", "寝台特急"],
 ["sound/atos/asakaze.mp3", "あさかぜ"],
 ["sound/atos/hokutosei.mp3", "北斗星"],
 ["sound/atos/kasiopea.mp3", "カシオペア"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/yukidesu.mp3", "行きです"],
 ["sound/atos/uenoyukidesu.mp3", "上野行きです"],
 ["sound/atos/uenoarrive.mp3", "上野行きがまいります"],
 ["sound/atos/takasakiar.mp3", "高崎行きがまいります"],
 ["sound/atos/takasakiyuki.mp3", "高崎行きです"],
 ["sound/atos/koganeiyukiarrv.mp3", "小金井行きがまいります"],
 ["sound/atos/takasaki.mp3", "高崎"],
 ["sound/atos/ueno.mp3", "上野"],
 ["sound/atos/honjo.mp3", "本庄"],
 ["sound/atos/koganei.mp3", "小金井"],
 ["sound/atos/utsunomiya.mp3", "宇都宮"],
 ["sound/atos/kumagaya.mp3", "熊谷"],
 ["sound/atos/hakata.mp3", "博多"],
 ["sound/atos/sapporo.mp3", "札幌"],
 ["sound/atos/fukaya.mp3", "深谷"],
 ["sound/atos/akita.mp3", "秋田"],
 ["sound/atos/aomori.mp3", "青森"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/mamonaku.mp3", "まもなく"],

 ["sound/atos/1bansenni.mp3", "1番線に"],
 ["sound/atos/.mp3", "2番線に"],
 ["sound/atos/.mp3", "3番線に"],
 ["sound/atos/.mp3", "4番線に"],
 ["sound/atos/.mp3", "5番線に"],
 ["sound/atos/.mp3", "6番線に"],
 ["sound/atos/.mp3", "7番線に"],
 ["sound/atos/.mp3", "8番線に"],
 ["sound/atos/.mp3", "9番線に"],
 ["sound/atos/.mp3", "10番線に"],
 ["sound/atos/.mp3", "11番線に"],
 ["sound/atos/.mp3", "12番線に"],
 ["sound/atos/.mp3", "13番線に"],
 ["sound/atos/.mp3", "14番線に"],
 ["sound/atos/.mp3", "15番線に"],
 ["sound/atos/.mp3", "16番線に"],
 ["sound/atos/.mp3", "17番線に"],
 ["sound/atos/.mp3", "18番線に"],
 ["sound/atos/.mp3", "19番線に"],
 ["sound/atos/.mp3", "20番線に"],
 ["sound/atos/.mp3", "21番線に"],
 ["sound/atos/.mp3", "22番線に"],


 ["sound/atos/groupga.mp3", "団体列車が"],
 ["sound/atos/kaisoressyaga.mp3", "回送列車が"],
 ["sound/atos/rinjiressyaga.mp3", "臨時列車が"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/yukiga.mp3", "行きが"],
 ["sound/atos/mairimasu.mp3", "まいります"],
 ["sound/atos/abunai.mp3", "危ないですから、黄色い線まで、お下がりください"],

 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/1bansenkara.mp3", "1番線から"],
 ["sound/atos/2bansenkara.mp3", "2番線から"],
 ["sound/atos/3bansenkara.mp3", "3番線から"],
 ["sound/atos/4bansenkara.mp3", "4番線から"],
 ["sound/atos/13bansenkara.mp3", "13番線から"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],
 ["sound/atos/hassyaitasi.mp3", "発車いたします"],
 ["sound/atos/gochui.mp3", "ご注意ください"],
 ["sound/atos/.mp3", ""],
 ["sound/atos/.mp3", ""],


 ["sound/null-250.mp3", "(無音0.25秒)"],
 ["sound/null-500.mp3", "(無音0.5秒)"],
 ["sound/null-750.mp3", "(無音0.75秒)"],
 ["sound/null-1000.mp3", "(無音1.0秒)"],
 ["sound/null-2000.mp3", "(無音2.0秒)"],
 ["sound/null-3000.mp3", "(無音3.0秒)"],

 ["sound/null-250.mp3", ""] //この最後の行は編集しないでください
 ]
